spring:
  profiles:
    active: local

  flyway:
    enabled: false
    locations: classpath:db/migrations/schema

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: admin