apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-s3
  namespace: kube-system
  labels:
    k8s-app: fluentd-s3
spec:
  selector:
    matchLabels:
      name: fluentd-s3
  template:
    metadata:
      labels:
        name: fluentd-s3
        k8s-app: fluentd-s3
    spec:
      containers:
      - name: fluentd-s3
        image: ccpgames/kubernetes-fluentd-s3:latest
        imagePullPolicy: Always
        env:
        - name: AWS_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: fluentd-s3-env-configmap
              key: AWS_S3_BUCKET
        - name: AWS_S3_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: fluentd-s3-env-configmap
              key: AWS_S3_BUCKET_PREFIX
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: fluentd-s3-env-configmap
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: fluentd-s3-env-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fluentd-s3-env-secret
              key: AWS_SECRET_ACCESS_KEY
        args:
        - --use-v1-config
        - -qq
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - name: varlog
          mountPath: /var/log 
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-conf
          mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-conf
        configMap:
          name: fluentd-conf-configmap