name: CI
on:
  push:
    paths:
      - 'apps/data/data-metrics/**'
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./apps/data/data-metrics
        run: |
          pip install pipenv
          pipenv install
      - name: Test with pytest
        working-directory: ./apps/data/data-metrics
        run: |
          pytest
