name: CI
on:
  push:
    paths:
      - 'apps/data/data-metrics/**'
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv
        working-directory: ./apps/data/data-metrics
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        working-directory: ./apps/data/data-metrics
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install

      - name: Run test suite
        working-directory: ./apps/data/data-metrics
        run: |
          pipenv run pytest
