name: Microservice - Metrics
on:
  push:
    paths:
      - './apps/microservices/ms-metrics/**'
  pull_request:
    paths:
      - './apps/microservices/ms-metrics/**'
  
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Maven Dependencies
        working-directory: ./apps/microservices/ms-metrics
        run: ./mvnw clean install -DskipTests

      - name: Maven Unit Testing
        working-directory: ./apps/microservices/ms-metrics
        run: ./mvnw test -Dtest.tags=unit

      - name: Maven Component Testing
        working-directory: ./apps/microservices/ms-metrics
        run: ./mvnw test -Dtest.tags=component

      - name: Maven Integration Testing
        working-directory: ./apps/microservices/ms-metrics
        run: ./mvnw test -Dtest.tags=integration

